### ISSUE TITLE
Binder not working

### ISSUE THREAD

**Issue by deborahdore** [iacopomasi/NLP#1]
Hello professor,
I believe the error is in some requirement that breaks the initialization of the repository when we try to open it on binder. Could you check when you've got time? Thanks

**Comment by iacopomasi** [comment]
Dear @deborahdore,

yes, unfortunately it has been a while that binder is not reliable anymore. I am also getting different errors that do not depend entirely on the repository, but on the fact that binder cannot handle all the requests it receives. I get errors such as `Too many users on this BinderHub! Try again soon.` or `internal server error`. I was now trying to relax the [requirements.txt](https://github.com/iacopomasi/NLP/blob/main/requirements.txt) to produce a lighter image  but I did not manage to fix it. Even in my other course in ML I saw the same problem. I was looking for replacements (i.e. google colab) but it is not that easy to do port it there. 

The best thing you can do is to download the repository locally, follow the guide on the google classroom called **Run the slides with Sapienza logo** and run the slides locally on your computer. 

PS I am going to update the repository from time to time so keep getting updates from it.

Thank you
